"""
YoloSide v2.0 - Main Window

The central MainWindow class that wires together:
- UI layout (from ui/home.py, generated by Qt Designer)
- YoloEngine (inference worker, runs in QThread)
- UIFunctions (window controls, animations, shadows)
- Configuration persistence via config/settings.py
"""

from PySide6.QtWidgets import (QMainWindow, QFileDialog, QMenu, QDialog,
                               QComboBox, QFrame, QVBoxLayout, QLabel,
                               QSizePolicy, QGraphicsDropShadowEffect,
                               QPushButton)
from PySide6.QtGui import QImage, QPixmap, QColor, QAction, QFont
from PySide6.QtCore import QTimer, QThread, Signal, QPoint, Qt

from ui.CustomMessageBox import MessageBox
from ui.home import Ui_MainWindow
from widgets.UIFunctions import UIFunctions
from config.settings import (
    AppSettings, load_fold_config, save_fold_config,
    load_ip_config, save_ip_config
)
from engine.inference import YoloEngine
from engine.task_config import (
    TaskType, TaskConfig, TASK_REGISTRY,
    get_task_display_names, task_type_from_display_name
)
from engine.batch_processor import BatchProcessor
from utils.capnums import Camera
from utils.rtsp_win import Window

import numpy as np
import json
import cv2
import os
import sys


# ── Path helpers for PyInstaller compatibility ────────────────────

def _resource_path(relative_path: str) -> str:
    """Get absolute path to a read-only resource file.
    Works in both dev mode and PyInstaller bundled mode.
    Project root = parent of the app/ directory (since mainwindow.py lives in app/)."""
    if getattr(sys, 'frozen', False):
        base = sys._MEIPASS
    else:
        # mainwindow.py is in app/ → go up one level to project root
        base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    return os.path.join(base, relative_path)


def _writable_path(relative_path: str) -> str:
    """Get absolute path for writable files (config, output).
    In bundled mode, writes next to the exe, not inside _MEIPASS.
    Creates parent directories as needed.
    Project root = parent of the app/ directory (since mainwindow.py lives in app/)."""
    if getattr(sys, 'frozen', False):
        base = os.path.dirname(sys.executable)
    else:
        # mainwindow.py is in app/ → go up one level to project root
        base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    full = os.path.join(base, relative_path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    return full


class MainWindow(QMainWindow, Ui_MainWindow):
    """Main application window for YoloSide."""

    main2yolo_begin_sgl = Signal()

    def __init__(self, parent=None):
        super(MainWindow, self).__init__(parent)

        # ── Basic interface setup ─────────────────────────────────
        self.setupUi(self)
        self.setAttribute(Qt.WA_TranslucentBackground)
        self.setWindowFlags(Qt.FramelessWindowHint)

        # Window controls, grips, animations
        UIFunctions.uiDefinitions(self)

        # Module shadows
        UIFunctions.shadow_style(self, self.Class_QF, QColor(162, 129, 247))
        UIFunctions.shadow_style(self, self.Target_QF, QColor(251, 157, 139))
        UIFunctions.shadow_style(self, self.Fps_QF, QColor(170, 128, 213))
        UIFunctions.shadow_style(self, self.Model_QF, QColor(64, 186, 193))

        # ── Add task type selector to settings panel ──────────────
        self._current_task_type = TaskType.DETECT
        self._task_model_selections: dict = {}  # TaskType → model_name
        self._setup_task_selector()

        # ── YoloEngine + QThread (must be before refresh_model_list)
        self.yolo_engine = YoloEngine()
        self.yolo_engine.set_task(self._current_task_type)

        # ── Cached camera list (enumerate only once per session ────
        #     to avoid opening/releasing the camera repeatedly which
        #     can leave DSHOW in a bad state.)
        self._cached_cams: list | None = None

        # ── Model folder monitoring ───────────────────────────────
        self.pt_list: list[str] = []
        self.refresh_model_list()
        self.Qtimer_ModelBox = QTimer(self)
        self.Qtimer_ModelBox.timeout.connect(self.ModelBoxRefre)
        self.Qtimer_ModelBox.start(2000)
        self.yolo_thread = QThread()
        self.yolo_engine.moveToThread(self.yolo_thread)

        # ── Connect YoloEngine signals ────────────────────────────
        self.yolo_engine.frame_processed.connect(self.on_frame_processed)
        self.yolo_engine.status_update.connect(self.show_status)
        self.yolo_engine.fps_update.connect(
            lambda x: self.fps_label.setText(f"{x:.1f}"))
        self.yolo_engine.progress_update.connect(
            lambda x: self.progress_bar.setValue(x))
        self.yolo_engine.total_classes.connect(
            lambda x: self.Class_num.setText(str(x)))
        self.yolo_engine.total_targets.connect(
            lambda x: self.Target_num.setText(str(x)))
        self.yolo_engine.inference_error.connect(
            lambda x: self.show_status(f"Error: {x}"))
        self.yolo_engine.processing_finished.connect(self.on_processing_finished)

        self.main2yolo_begin_sgl.connect(self.yolo_engine.run)

        # ── Model parameter controls ──────────────────────────────
        self.model_box.currentTextChanged.connect(self.on_model_changed)
        self.iou_spinbox.valueChanged.connect(
            lambda x: self.change_val(x, 'iou_spinbox'))
        self.iou_slider.valueChanged.connect(
            lambda x: self.change_val(x, 'iou_slider'))
        self.conf_spinbox.valueChanged.connect(
            lambda x: self.change_val(x, 'conf_spinbox'))
        self.conf_slider.valueChanged.connect(
            lambda x: self.change_val(x, 'conf_slider'))
        self.speed_spinbox.valueChanged.connect(
            lambda x: self.change_val(x, 'speed_spinbox'))
        self.speed_slider.valueChanged.connect(
            lambda x: self.change_val(x, 'speed_slider'))

        # ── Initial display values ────────────────────────────────
        self.Class_num.setText('--')
        self.Target_num.setText('--')
        self.fps_label.setText('--')
        self.Model_name.setText(self.model_box.currentText() or '--')

        # ── Source selection buttons ──────────────────────────────
        self.src_file_button.clicked.connect(self.open_src_file)
        self.src_cam_button.clicked.connect(self.chose_cam)
        self.src_rtsp_button.clicked.connect(self.chose_rtsp)

        # ── Run / Stop buttons ────────────────────────────────────
        self.run_button.clicked.connect(self.run_or_continue)
        self.stop_button.clicked.connect(self.stop)

        # ── Save options ──────────────────────────────────────────
        self.save_res_button.toggled.connect(self.is_save_res)
        self.save_txt_button.toggled.connect(self.is_save_txt)

        # ── Menu / Settings buttons ───────────────────────────────
        self.ToggleBotton.clicked.connect(
            lambda: UIFunctions.toggleMenu(self, True))
        self.settings_button.clicked.connect(
            lambda: UIFunctions.settingBox(self, True))

        # ── Inference state tracking ──────────────────────────────
        self._inference_active: bool = False

        # ── Batch processing ──────────────────────────────────────
        self._setup_batch_ui()
        self._batch_processor: BatchProcessor | None = None
        self._batch_thread: QThread | None = None

        # ── Log output panel ──────────────────────────────────────
        self._setup_log_panel()

        # ── Load persisted config ─────────────────────────────────
        self.load_config()

        # ── UI polish ──────────────────────────────────────────────
        self.setWindowTitle("YoloSide v2.0")
        self.VersionLabel.setText("Version: 2.0")
        self.splitter.setSizes([500, 500])  # 50/50 default split
        # Increase combo heights for better dropdown usability
        self.model_box.setMinimumSize(170, 24)
        self.model_box.setMaximumSize(170, 24)
        # Remove bottom status bar — log panel now handles all messages
        self.below.hide()

        # Set initial model
        self._update_model_list_for_task(self._current_task_type)

    # ── Task Type Selector ────────────────────────────────────────

    def _setup_task_selector(self):
        """Programmatically add a task type combo to the settings panel."""
        # Create frame matching the style of other settings blocks
        self.Task_QF = QFrame(self.prm_page)
        self.Task_QF.setObjectName("Task_QF")
        self.Task_QF.setMinimumSize(190, 70)
        self.Task_QF.setMaximumSize(190, 70)
        self.Task_QF.setStyleSheet("""
            QFrame#Task_QF {
                border:2px solid rgba(255, 255, 255, 70);
                border-radius:15px;
            }
        """)
        layout = QVBoxLayout(self.Task_QF)
        layout.setContentsMargins(9, 5, 9, 5)
        layout.setSpacing(4)

        # Title button (styled like other section headers)
        title_btn = QLabel("Task Type")
        title_btn.setStyleSheet("""
            color: rgba(255, 255, 255, 199);
            font: 700 13pt "Nirmala UI";
            padding-left: 5px;
        """)
        title_btn.setMinimumHeight(24)
        layout.addWidget(title_btn)

        # Combo box
        self.task_combo = QComboBox()
        self.task_combo.setObjectName("task_combo")
        self.task_combo.setMinimumSize(170, 24)
        self.task_combo.setMaximumSize(170, 24)
        self.task_combo.setStyleSheet("""
            QComboBox {
                background-color: rgba(255,255,255,90);
                color: rgba(0, 0, 0, 200);
                font: 600 9pt "Segoe UI";
                border: 1px solid lightgray;
                border-radius: 10px;
                padding-left: 15px;
            }
            QComboBox:on { border: 1px solid #63acfb; }
            QComboBox::drop-down {
                width: 22px;
                border-left: 1px solid lightgray;
                border-top-right-radius: 15px;
                border-bottom-right-radius: 15px;
            }
            QComboBox::drop-down:on { border-left: 1px solid #63acfb; }
            QComboBox QAbstractItemView {
                border: none;
                outline: none;
                padding: 10px;
                background-color: rgb(223, 188, 220);
            }
        """)
        self.task_combo.addItems(get_task_display_names())
        self.task_combo.setCurrentIndex(0)  # Default: Detection
        self.task_combo.currentIndexChanged.connect(self.on_task_changed)
        layout.addWidget(self.task_combo)

        # Insert at position 1 in the settings layout (after "Settings" label)
        self.verticalLayout_22.insertWidget(1, self.Task_QF)

    def on_task_changed(self, index: int):
        """Handle task type selection change."""
        display_names = get_task_display_names()
        if 0 <= index < len(display_names):
            task_type = task_type_from_display_name(display_names[index])
            self._current_task_type = task_type
            task_config = TASK_REGISTRY[task_type]

            # Update title
            self.char_label.setText(task_config.result_label)

            # Update engine
            self.yolo_engine.set_task(task_type)

            # Update model list for this task
            self._update_model_list_for_task(task_type)

            self.show_status(f"Task: {task_config.display_name}")

    def _update_model_list_for_task(self, task_type: TaskType):
        """Populate model_box with locally available models for the given task."""
        task_config = TASK_REGISTRY[task_type]
        registry_models = set(task_config.available_models)

        # Get locally downloaded models that match this task.
        # Use _writable_path so models survive app restarts
        # (in bundled mode, _MEIPASS is a temp dir that gets wiped).
        models_dir = _writable_path('models')
        local_models = []
        if os.path.isdir(models_dir):
            for f in os.listdir(models_dir):
                if f.endswith('.pt'):
                    local_models.append(f)

        # Show: local models that are in the registry for this task
        # + any local models not in registry (custom models)
        local_registry = [m for m in local_models if m in registry_models]
        local_registry.sort(key=lambda x: os.path.getsize(os.path.join(models_dir, x))
                           if os.path.exists(os.path.join(models_dir, x)) else 0)

        # Add marker for downloadable models
        available = list(local_registry)
        # Also add models that can be downloaded (marked with 🌐)
        for m in task_config.available_models:
            if m not in local_models:
                available.append(f"🌐 {m}")

        current = self.model_box.currentText()
        # Strip 🌐 prefix for comparison
        current_clean = current.replace("🌐 ", "") if current else ""

        # Block signals during rebuild — addItems() would otherwise fire
        # currentTextChanged → on_model_changed → overwrite _task_model_selections
        # BEFORE our selection logic below gets a chance to run.
        self.model_box.blockSignals(True)
        self.model_box.clear()
        self.model_box.addItems(available)

        # Restore selection priority:
        # 1) User's previously saved choice for this task type
        # 2) Current selection if still in the list
        # 3) First available local model (if any)
        # 4) Leave empty (user must pick)
        saved = self._task_model_selections.get(task_type, None)
        if saved and saved in local_registry:
            self.model_box.setCurrentText(saved)
        elif saved and saved in task_config.available_models:
            # Model not downloaded yet — select it with 🌐 prefix
            self.model_box.setCurrentText(f"🌐 {saved}")
        elif current_clean in local_registry:
            self.model_box.setCurrentText(current_clean)
        elif local_registry:
            self.model_box.setCurrentText(local_registry[0])

        self.model_box.blockSignals(False)
        # Apply the final selection — use the passed task_type
        # (not self._current_task_type, which may be stale)
        final = self.model_box.currentText()
        final_clean = final.replace("🌐 ", "") if final else ""
        # Only call on_model_changed if the model actually DIFFERS from
        # what the engine already has.  This prevents the 2-second
        # ModelBoxRefre timer from nuking _model during active inference.
        # _model_name is a full path (e.g. D:\...\models\yolov8n.pt),
        # final_clean is just the filename — compare basenames.
        engine_basename = os.path.basename(self.yolo_engine._model_name) if self.yolo_engine._model_name else ""
        if final and final_clean != engine_basename:
            self.on_model_changed(final, task_type=task_type)

        self.pt_list = sorted(local_models)  # Update cached list (sorted for ModelBoxRefre compare)

    # ── Batch Processing UI & Logic ──────────────────────────────

    def _setup_batch_ui(self):
        """Add batch processing controls to the settings panel."""
        self.Batch_QF = QFrame(self.prm_page)
        self.Batch_QF.setObjectName("Batch_QF")
        self.Batch_QF.setMinimumSize(190, 90)
        self.Batch_QF.setMaximumSize(190, 90)
        self.Batch_QF.setStyleSheet("""
            QFrame#Batch_QF {
                border:2px solid rgba(255, 255, 255, 70);
                border-radius:15px;
            }
        """)
        layout = QVBoxLayout(self.Batch_QF)
        layout.setContentsMargins(9, 5, 9, 9)
        layout.setSpacing(6)

        # Title
        title = QLabel("Batch Process")
        title.setStyleSheet("""
            color: rgba(255, 255, 255, 199);
            font: 700 13pt "Nirmala UI";
            padding-left: 5px;
        """)
        title.setMinimumHeight(22)
        layout.addWidget(title)

        # Folder selector button
        self.batch_folder_btn = QPushButton("Select Folder")
        self.batch_folder_btn.setCursor(Qt.PointingHandCursor)
        self.batch_folder_btn.setStyleSheet("""
            QPushButton {
                background-color: rgba(255,255,255,90);
                color: rgba(0, 0, 0, 200);
                font: 600 9pt "Segoe UI";
                border: 1px solid lightgray;
                border-radius: 10px;
                padding: 4px 10px;
            }
            QPushButton:hover {
                background-color: rgba(255,255,255,150);
            }
        """)
        self.batch_folder_btn.clicked.connect(self._select_batch_folder)
        layout.addWidget(self.batch_folder_btn)

        # Folder path label (shown after selection)
        self.batch_path_label = QLabel("")
        self.batch_path_label.setStyleSheet("""
            color: rgba(255, 255, 255, 160);
            font: 7pt "Segoe UI";
            padding-left: 2px;
        """)
        self.batch_path_label.setWordWrap(True)
        self.batch_path_label.setMaximumHeight(20)
        layout.addWidget(self.batch_path_label)

        self.verticalLayout_22.addWidget(self.Batch_QF)

    def _setup_log_panel(self):
        """Create a dedicated scrollable log output area in the main content."""
        from PySide6.QtWidgets import QTextEdit

        self.Log_QF = QFrame(self.content)
        self.Log_QF.setObjectName("Log_QF")
        self.Log_QF.setMinimumSize(0, 75)
        self.Log_QF.setMaximumSize(16777215, 130)
        self.Log_QF.setStyleSheet("""
            QFrame#Log_QF {
                background-color: rgb(238, 242, 255);
                border:2px solid rgb(255, 255, 255);
                border-radius:15px;
            }
        """)
        layout = QVBoxLayout(self.Log_QF)
        layout.setContentsMargins(8, 4, 8, 8)
        layout.setSpacing(0)

        self.log_text = QTextEdit()
        self.log_text.setReadOnly(True)
        self.log_text.setPlaceholderText("Ready — select a source and start inference...")
        self.log_text.setContextMenuPolicy(Qt.CustomContextMenu)
        self.log_text.customContextMenuRequested.connect(self._log_context_menu)
        self.log_text.setStyleSheet("""
            QTextEdit {
                background-color: rgba(235, 237, 242, 250);
                color: rgba(30, 28, 48, 235);
                font: 600 9pt "Consolas";
                border: none;
                border-radius: 10px;
                padding: 6px 8px;
            }
            QScrollBar:vertical {
                width: 6px;
                background: transparent;
                margin: 2px;
            }
            QScrollBar::handle:vertical {
                background: rgba(140, 130, 180, 100);
                border-radius: 3px;
                min-height: 20px;
            }
            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {
                height: 0px;
            }
        """)
        layout.addWidget(self.log_text)

        # Insert after Pause_QF in the main_content vertical layout
        self.main_content.addWidget(self.Log_QF)

    def _log_context_menu(self, pos):
        """Right-click context menu for the log panel."""
        menu = QMenu(self.log_text)
        clear_action = menu.addAction("Clear Log")
        copy_action = menu.addAction("Copy All")
        action = menu.exec(self.log_text.mapToGlobal(pos))
        if action == clear_action:
            self.log_text.clear()
        elif action == copy_action:
            from PySide6.QtWidgets import QApplication
            QApplication.clipboard().setText(self.log_text.toPlainText())
            self.show_status("Log copied to clipboard")

    def _log(self, msg: str):
        """Append a timestamped message to the log panel."""
        if not hasattr(self, 'log_text'):
            return
        from datetime import datetime
        ts = datetime.now().strftime("%H:%M:%S")
        self.log_text.append(f"[{ts}] {msg}")
        # Auto-scroll to bottom
        from PySide6.QtWidgets import QScrollBar
        vbar = self.log_text.verticalScrollBar()
        if vbar:
            vbar.setValue(vbar.maximum())

    def _select_batch_folder(self):
        """Open folder picker and store path for later batch processing."""
        folder = QFileDialog.getExistingDirectory(
            self, "Select Image Folder", os.getcwd())
        if not folder:
            return
        self._batch_folder = folder
        # Show brief folder name in the batch section
        disp = os.path.basename(folder)
        if len(disp) > 22:
            disp = disp[:20] + "..."
        self.batch_path_label.setText(f"📁 {disp}")
        self._log(f"Batch folder selected: {folder}")
        self.show_status(f"Batch ready — {folder}  (click ▶ to start)")

    def _run_batch(self, folder: str):
        """Set up and start batch processing on the given folder."""
        # Stop any running inference
        self.stop()

        self._log(f"Starting batch processing: {folder}")

        # Create batch processor
        model_name = self.model_box.currentText().replace("🌐 ", "")
        model_path = f"{_writable_path('models')}/{model_name}" if "/" not in model_name else model_name

        self._batch_processor = BatchProcessor()
        self._batch_processor.set_task(self._current_task_type)
        self._batch_processor.set_model(model_path)
        self._batch_processor.conf_thres = self.yolo_engine.conf_thres
        self._batch_processor.iou_thres = self.yolo_engine.iou_thres
        self._batch_processor.save_res = True
        self._batch_processor.save_txt = self.yolo_engine.save_txt

        # Create thread
        self._batch_thread = QThread()
        self._batch_processor.moveToThread(self._batch_thread)

        # Connect signals
        self._batch_processor.file_progress.connect(
            lambda cur, tot: self._log(f"Batch: {cur}/{tot} images"))
        self._batch_processor.file_done.connect(
            lambda fname, st: self._log(
                f"  {'✓' if st == 'ok' else '✗'} {fname}" +
                (f" — {st}" if st != 'ok' else '')))
        self._batch_processor.batch_summary.connect(
            lambda s: self.show_status(
                f"Batch done: {s['success']}/{s['total']} in {s['elapsed']:.1f}s → {s.get('output_dir', '')}"))
        self._batch_processor.status_update.connect(
            lambda msg: self._log(msg))
        self._batch_processor.batch_finished.connect(
            lambda: self._cleanup_batch())
        # Show original image in left panel, annotated in right panel
        self._batch_processor.original_image.connect(
            lambda img: self.show_image(img, self.pre_video))
        self._batch_processor.current_image.connect(
            lambda img: self.show_image(img, self.res_video))

        # Reset batch folder after starting
        self._batch_folder = None
        self.batch_path_label.setText("")

        # Run
        self._batch_thread.started.connect(
            lambda: self._batch_processor.run(folder))
        self._batch_thread.start()

    def _cleanup_batch(self):
        """Clean up batch processing thread."""
        if self._batch_thread and self._batch_thread.isRunning():
            self._batch_thread.quit()
            self._batch_thread.wait(3000)

    # ── Image display ─────────────────────────────────────────────

    @staticmethod
    def show_image(img_src, label):
        try:
            ih, iw, _ = img_src.shape
            w = label.geometry().width()
            h = label.geometry().height()
            if iw / w > ih / h:
                scal = w / iw
                nw, nh = w, int(scal * ih)
            else:
                scal = h / ih
                nw, nh = int(scal * iw), h
            img_src_ = cv2.resize(img_src, (nw, nh))
            frame = cv2.cvtColor(img_src_, cv2.COLOR_BGR2RGB)
            img = QImage(frame.data, frame.shape[1], frame.shape[0],
                         frame.shape[2] * frame.shape[1], QImage.Format_RGB888)
            label.setPixmap(QPixmap.fromImage(img))
        except Exception as e:
            print(repr(e))

    # ── YoloEngine signal handlers ────────────────────────────────

    def on_frame_processed(self, raw_frame: np.ndarray, annotated: np.ndarray):
        self.show_image(raw_frame, self.pre_video)
        self.show_image(annotated, self.res_video)

    def on_processing_finished(self):
        self._inference_active = False
        self.save_res_button.setEnabled(True)
        self.save_txt_button.setEnabled(True)
        self.run_button.setChecked(False)
        self.progress_bar.setValue(0)
        self.show_status("Processing finished.")

    # ── Run / Pause ───────────────────────────────────────────────

    def run_or_continue(self):
        # Check for batch folder first — batch mode overrides normal inference
        batch_folder = getattr(self, '_batch_folder', None)
        if batch_folder and os.path.isdir(batch_folder):
            self._run_batch(batch_folder)
            return

        source = self.yolo_engine._source if self.yolo_engine._source else ''
        if not source:
            self.show_status(
                'Please select a video source before starting detection...')
            self.run_button.setChecked(False)
        else:
            if self.run_button.isChecked():
                if self._inference_active:
                    # Already running — just unpause
                    self.yolo_engine.pause(False)
                    self.show_status('Detecting...')
                else:
                    # Start fresh inference
                    self.run_button.setChecked(True)
                    self.save_txt_button.setEnabled(False)
                    self.save_res_button.setEnabled(False)
                    self.show_status('Detecting...')
                    # The worker thread stays alive across runs
                    # (we never quit() it — just stop the engine).
                    if not self.yolo_thread.isRunning():
                        self.yolo_thread.start()
                    self._inference_active = True
                    self.main2yolo_begin_sgl.emit()
            else:
                self.yolo_engine.pause(True)
                self.show_status("Pause...")
                self.run_button.setChecked(False)

    def show_status(self, msg):
        self.status_bar.setText(msg)
        self._log(msg)

    # ── Source: local file ────────────────────────────────────────

    def open_src_file(self):
        config_file = _writable_path('config/fold.json')
        try:
            config = json.load(open(config_file, 'r', encoding='utf-8'))
            open_fold = config.get('open_fold', os.getcwd())
        except (FileNotFoundError, json.JSONDecodeError, KeyError):
            open_fold = os.getcwd()
            config = {'open_fold': open_fold}
        if not os.path.exists(open_fold):
            open_fold = os.getcwd()
        name, _ = QFileDialog.getOpenFileName(
            self, 'Video/image', open_fold,
            "Pic File(*.mp4 *.mkv *.avi *.flv *.jpg *.png)")
        if name:
            # stop() must come BEFORE set_source() — it clears _source.
            # (Matches the pattern in chose_cam() and load_rtsp().)
            self.stop()
            self.yolo_engine.set_source(name)
            self.show_status(f'Load File: {os.path.basename(name)}')
            config['open_fold'] = os.path.dirname(name)
            try:
                with open(config_file, 'w', encoding='utf-8') as f:
                    json.dump(config, f, ensure_ascii=False, indent=2)
            except Exception:
                pass

    # ── Source: camera ────────────────────────────────────────────

    def chose_cam(self):
        try:
            self.stop()
            # Only pop "loading" + enumerate if we haven't already cached
            if self._cached_cams is None:
                MessageBox(
                    self.close_button, title='Note',
                    text='loading camera...', time=2000, auto=True).exec()
                _, self._cached_cams = Camera().get_cam_num()

            cams = self._cached_cams
            if not cams:
                self.show_status('No camera detected.')
                return

            if len(cams) == 1:
                # Only one camera — select it directly
                self.yolo_engine.set_source(str(cams[0]))
                self.show_status(f'Loading camera: {cams[0]}')
                return

            # ── Multiple cameras — show a centered selection dialog ──
            dialog = QDialog(self)
            dialog.setWindowTitle("Select Camera")
            dialog.setFixedSize(280, 55 + 48 * len(cams))
            dialog.setWindowFlags(Qt.Dialog)
            dialog.setStyleSheet('''
                QDialog {
                    background-color: qlineargradient(
                        x0:0, y0:0, x1:0, y1:1,
                        stop:0.0 rgb(88, 72, 171),
                        stop:0.5 rgb(107, 96, 196),
                        stop:1.0 rgb(130, 110, 220)
                    );
                }
                QPushButton {
                    color: white;
                    background-color: rgba(255, 255, 255, 40);
                    font: 700 12pt "Microsoft YaHei UI";
                    border: 1px solid rgba(255, 255, 255, 100);
                    border-radius: 8px;
                    padding: 10px;
                    margin: 3px 10px;
                }
                QPushButton:hover {
                    background-color: rgba(255, 255, 255, 90);
                    color: rgb(60, 40, 130);
                }
                QLabel {
                    color: white;
                    font: 700 13pt "Microsoft YaHei UI";
                }
            ''')

            layout = QVBoxLayout(dialog)
            layout.setContentsMargins(20, 15, 20, 18)
            layout.setSpacing(8)

            title_label = QLabel("🎥  Select Camera")
            title_label.setAlignment(Qt.AlignCenter)
            layout.addWidget(title_label)

            for cam in cams:
                btn = QPushButton(f"Camera {cam}")
                btn.setCursor(Qt.PointingHandCursor)
                btn.clicked.connect(
                    lambda checked, c=cam: self._on_camera_selected(dialog, c))
                layout.addWidget(btn)

            # Center on main window
            center = self.geometry().center()
            dialog.move(center.x() - dialog.width() // 2,
                        center.y() - dialog.height() // 2)

            self._selected_cam = None
            dialog.exec()

            if self._selected_cam is not None:
                self.yolo_engine.set_source(str(self._selected_cam))
                self.show_status(f'Loading camera: {self._selected_cam}')
        except Exception as e:
            self.show_status(f'{e}')

    def _on_camera_selected(self, dialog, cam_index):
        """Store the selected camera index and close the dialog."""
        self._selected_cam = cam_index
        dialog.accept()

    # ── Source: RTSP ──────────────────────────────────────────────

    def chose_rtsp(self):
        self.rtsp_window = Window()
        config_file = _writable_path('config/ip.json')
        if not os.path.exists(config_file):
            ip = "rtsp://admin:admin888@192.168.1.2:555"
            with open(config_file, 'w', encoding='utf-8') as f:
                json.dump({"ip": ip}, f, ensure_ascii=False, indent=2)
        else:
            ip = json.load(open(config_file, 'r', encoding='utf-8'))['ip']
        self.rtsp_window.rtspEdit.setText(ip)
        self.rtsp_window.show()
        self.rtsp_window.rtspButton.clicked.connect(
            lambda: self.load_rtsp(self.rtsp_window.rtspEdit.text()))

    def load_rtsp(self, ip):
        try:
            self.stop()
            MessageBox(
                self.close_button, title='提示', text='加载 rtsp...',
                time=1000, auto=True).exec()
            self.yolo_engine.set_source(ip)
            with open(_writable_path('config/ip.json'), 'w', encoding='utf-8') as f:
                json.dump({"ip": ip}, f, ensure_ascii=False, indent=2)
            self.show_status(f'Loading rtsp: {ip}')
            self.rtsp_window.close()
        except Exception as e:
            self.show_status(f'{e}')

    # ── Save options ──────────────────────────────────────────────

    def is_save_res(self):
        checked = self.save_res_button.checkState() == Qt.CheckState.Checked
        self.yolo_engine.save_res = checked
        self.show_status(
            'NOTE: Run image results will be saved.' if checked
            else 'NOTE: Run image results are not saved.')

    def is_save_txt(self):
        checked = self.save_txt_button.checkState() == Qt.CheckState.Checked
        self.yolo_engine.save_txt = checked
        self.show_status(
            'NOTE: Labels results will be saved.' if checked
            else 'NOTE: Labels results are not saved.')

    # ── Config ────────────────────────────────────────────────────

    def load_config(self):
        config_file = _writable_path('config/setting.json')
        if not os.path.exists(config_file):
            iou, conf, rate = 0.26, 0.33, 10
            save_res, save_txt = 0, 0
            with open(config_file, 'w', encoding='utf-8') as f:
                json.dump({
                    "iou": iou, "conf": conf, "rate": rate,
                    "save_res": save_res, "save_txt": save_txt
                }, f, ensure_ascii=False, indent=2)
        else:
            config = json.load(open(config_file, 'r', encoding='utf-8'))
            if len(config) != 5:
                iou, conf, rate = 0.26, 0.33, 10
                save_res, save_txt = 0, 0
            else:
                iou = config['iou']
                conf = config['conf']
                rate = config['rate']
                save_res = config['save_res']
                save_txt = config['save_txt']

        self.yolo_engine.iou_thres = iou
        self.yolo_engine.conf_thres = conf
        self.yolo_engine.speed_thres = rate
        self.yolo_engine.save_res = (save_res != 0)
        self.yolo_engine.save_txt = (save_txt != 0)

        self.iou_spinbox.setValue(iou)
        self.iou_slider.setValue(int(iou * 100))
        self.conf_spinbox.setValue(conf)
        self.conf_slider.setValue(int(conf * 100))
        self.speed_spinbox.setValue(rate)
        self.speed_slider.setValue(rate)
        self.save_res_button.setCheckState(Qt.CheckState(save_res))
        self.save_txt_button.setCheckState(Qt.CheckState(save_txt))
        self.run_button.setChecked(False)
        self.show_status("Welcome~")

    # ── Stop ──────────────────────────────────────────────────────

    def stop(self):
        # Always call engine.stop() — it's safe even when idle
        # (all internals check for None) and it clears _source.
        # Previously the _inference_active guard skipped it when
        # inference hadn't started, leaking the source selection.
        self.yolo_engine.stop()
        self._inference_active = False
        self.run_button.setChecked(False)
        self.save_res_button.setEnabled(True)
        self.save_txt_button.setEnabled(True)
        self.pre_video.clear()
        self.res_video.clear()
        self.progress_bar.setValue(0)
        self.Class_num.setText('--')
        self.Target_num.setText('--')
        self.fps_label.setText('--')
        self.show_status("Stopped.")

    # ── Parameter changes ─────────────────────────────────────────

    def change_val(self, x, flag):
        if flag == 'iou_spinbox':
            self.iou_slider.setValue(int(x * 100))
        elif flag == 'iou_slider':
            self.iou_spinbox.setValue(x / 100)
            self.yolo_engine.iou_thres = x / 100
            self.show_status(f'IOU Threshold: {x / 100:.2f}')
        elif flag == 'conf_spinbox':
            self.conf_slider.setValue(int(x * 100))
        elif flag == 'conf_slider':
            self.conf_spinbox.setValue(x / 100)
            self.yolo_engine.conf_thres = x / 100
            self.show_status(f'Conf Threshold: {x / 100:.2f}')
        elif flag == 'speed_spinbox':
            self.speed_slider.setValue(x)
        elif flag == 'speed_slider':
            self.speed_spinbox.setValue(x)
            self.yolo_engine.speed_thres = x
            self.show_status(f'Delay: {x} ms')

    # ── Model management ──────────────────────────────────────────

    def on_model_changed(self, name: str, task_type=None):
        if name:
            if task_type is None:
                task_type = self._current_task_type
            # Strip 🌐 prefix for downloadable models
            clean_name = name.replace("🌐 ", "")
            # Use writable path so ultralytics can persist downloaded models
            model_path = f"{_writable_path('models')}/{clean_name}" if "/" not in clean_name else clean_name
            self.yolo_engine.set_model(model_path)
            self.Model_name.setText(clean_name)
            self.show_status(f'Model: {clean_name}')
            # Remember user's choice for this task type
            self._task_model_selections[task_type] = clean_name

    def refresh_model_list(self):
        """Populate model_box based on current task type."""
        self._update_model_list_for_task(self._current_task_type)

    def ModelBoxRefre(self):
        """Periodic check for new/deleted model files."""
        # Don't refresh while the user is browsing the dropdown
        if self.model_box.view().isVisible():
            return
        models_dir = _writable_path('models')
        if not os.path.isdir(models_dir):
            return
        current_all = sorted(
            [f for f in os.listdir(models_dir) if f.endswith('.pt')],
            key=lambda x: os.path.getsize(os.path.join(models_dir, x)))
        if current_all != self.pt_list:
            self.refresh_model_list()

    # ── Window events ─────────────────────────────────────────────

    def mousePressEvent(self, event):
        self.dragPos = event.globalPosition().toPoint()

    def resizeEvent(self, event):
        UIFunctions.resize_grips(self)

    def closeEvent(self, event):
        config = {
            'iou': self.iou_spinbox.value(),
            'conf': self.conf_spinbox.value(),
            'rate': self.speed_spinbox.value(),
            'save_res': 0 if self.save_res_button.checkState() == Qt.Unchecked else 2,
            'save_txt': 0 if self.save_txt_button.checkState() == Qt.Unchecked else 2,
        }
        try:
            config_file = _writable_path('config/setting.json')
            with open(config_file, 'w', encoding='utf-8') as f:
                json.dump(config, f, ensure_ascii=False, indent=2)
        except Exception:
            pass
        if self._batch_thread and self._batch_thread.isRunning():
            self._batch_processor.stop()
            self._batch_thread.quit()
            self._batch_thread.wait(3000)
        if self._inference_active:
            self.yolo_engine.stop()
        if self.yolo_thread.isRunning():
            self.yolo_thread.quit()
            self.yolo_thread.wait(3000)
        sys.exit(0)
